# Generated by Django 4.1.4 on 2023-07-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10, null=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('contacts', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('statut', models.CharField(choices=[('M', 'Marié(e)'), ('C', 'Celibataire(e)')], max_length=10, null=True)),
                ('nbrEnfant', models.IntegerField(blank=True, null=True)),
                ('pays', models.CharField(max_length=50, null=True)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('quartier', models.CharField(max_length=100, null=True)),
                ('codePostal', models.CharField(max_length=10, null=True)),
                ('cni', models.CharField(max_length=20, null=True)),
                ('cnss', models.CharField(max_length=10, null=True)),
                ('hautDegreQualification', models.CharField(max_length=50, null=True)),
                ('certification', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDepartement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=10, null=True)),
                ('dateNaissance', models.DateField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo/')),
                ('contacts', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('statut', models.CharField(choices=[('M', 'Marié(e)'), ('C', 'Celibataire(e)')], max_length=10, null=True)),
                ('nbrEnfant', models.IntegerField(blank=True, null=True)),
                ('pays', models.CharField(max_length=50, null=True)),
                ('ville', models.CharField(max_length=50, null=True)),
                ('quartier', models.CharField(max_length=100, null=True)),
                ('codePostal', models.CharField(max_length=10, null=True)),
                ('cni', models.CharField(max_length=20, null=True)),
                ('cnss', models.CharField(max_length=10, null=True)),
                ('hautDegreQualification', models.CharField(max_length=50, null=True)),
                ('certification', models.CharField(max_length=100, null=True)),
                ('matricule', models.CharField(max_length=20, null=True, unique=True)),
                ('poste', models.CharField(max_length=150, null=True)),
                ('contrat', models.CharField(max_length=10, null=True)),
                ('dateEmbauche', models.DateField(null=True)),
                ('salaireBase', models.FloatField(null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Monapp.departement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureNormalTravail', models.IntegerField()),
                ('heureSupplementaire', models.IntegerField()),
                ('totalHeureTravail', models.IntegerField()),
                ('revenuBrut', models.FloatField()),
                ('cotisationSociale', models.FloatField()),
                ('impotRevenu', models.FloatField()),
                ('revenuNet', models.FloatField(null=True)),
                ('salarie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarie', to='Monapp.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heureArrive', models.TimeField()),
                ('heureDepart', models.TimeField(blank=True, null=True)),
                ('salarieEnregistrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Monapp.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titreDocument', models.CharField(max_length=100)),
                ('descritifDocuemnt', models.TextField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('destinataire', models.ManyToManyField(to='Monapp.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutConge', models.DateField()),
                ('dateFinConge', models.DateField()),
                ('typeConge', models.CharField(max_length=50)),
                ('descriptifConge', models.TextField(max_length=300)),
                ('statutConge', models.CharField(blank=True, choices=[('0', 'Approuve'), ('1', 'Refuser')], max_length=10, null=True)),
                ('motifstatutConge', models.TextField(blank=True, max_length=300, null=True)),
                ('salarieConge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Monapp.salarie')),
            ],
        ),
    ]
