# Generated by Django 4.1.4 on 2023-07-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salarie',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
