# Generated by Django 4.1.4 on 2023-07-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monapp', '0002_administrateur_password_administrateur_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='matricule',
        ),
    ]
