# Generated by Django 4.1.4 on 2023-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monapp', '0003_remove_salarie_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='password',
            field=models.CharField(default='madema', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='password',
            field=models.CharField(default='madema', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='administrateur',
            unique_together={('nom', 'prenom')},
        ),
        migrations.AlterUniqueTogether(
            name='salarie',
            unique_together={('nom', 'prenom')},
        ),
    ]
