# Generated by Django 4.1.4 on 2023-07-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Monapp', '0005_alter_administrateur_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='motifstatutConge',
        ),
    ]
