# Generated by Django 4.2.2 on 2023-07-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monapp', '0006_remove_conge_motifstatutconge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='statutConge',
            field=models.CharField(blank=True, choices=[('En attente', 'En attente'), ('Approuve', 'Approuve'), ('Refuser', 'Refuser')], default='En attente', max_length=10, null=True),
        ),
    ]
