# Generated by Django 4.1.4 on 2023-07-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='departement',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
