# Generated by Django 4.2.2 on 2023-06-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0002_alter_document_titredocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heureNormalTravail', models.IntegerField()),
                ('heureSupplementaire', models.IntegerField()),
                ('totalHeureTravail', models.IntegerField()),
                ('revenuBrut', models.FloatField()),
                ('CotisationSociale', models.FloatField()),
                ('impotRevenu', models.FloatField()),
                ('revenuNet', models.FloatField()),
                ('salarie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserDoc.salarie')),
            ],
        ),
    ]
