# Generated by Django 4.2.2 on 2023-06-28 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0003_paie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paie',
            old_name='CotisationSociale',
            new_name='cotisationSociale',
        ),
        migrations.RemoveField(
            model_name='paie',
            name='revenuNet',
        ),
        migrations.AlterField(
            model_name='paie',
            name='salarie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salarie', to='UserDoc.salarie'),
        ),
    ]
