# Generated by Django 4.2.2 on 2023-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0004_rename_cotisationsociale_paie_cotisationsociale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paie',
            name='revenuNet',
            field=models.FloatField(null=True),
        ),
    ]
