# Generated by Django 4.2.2 on 2023-06-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0006_conge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField()),
                ('heureArrive', models.TimeField()),
                ('heureDepart', models.TimeField()),
                ('salarieEnregistrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserDoc.salarie')),
            ],
        ),
    ]
