# Generated by Django 4.2.2 on 2023-06-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0008_alter_enregistrement_heuredepart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='heureDepart',
            field=models.TimeField(null=True),
        ),
    ]
