# Generated by Django 4.1.4 on 2023-06-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0013_alter_salarie_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarie',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserDoc.departement'),
        ),
    ]
