# Generated by Django 4.1.4 on 2023-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0014_alter_salarie_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='statutConge',
            field=models.CharField(blank=True, choices=[('0', 'Approuve'), ('1', 'Refuser')], max_length=10, null=True),
        ),
    ]
