# Generated by Django 4.2.2 on 2023-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0015_alter_conge_statutconge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarie',
            name='departement',
            field=models.CharField(choices=[('1', 'Informatique'), ('2', 'Commerciale'), ('3', 'Techniciens')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
