# Generated by Django 4.2.2 on 2023-07-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDoc', '0017_rename_cinutilisateur_administrateur_cni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
